spring.application.name=UserStory-1
spring.profiles.active=jpa

# Settings H2 Database
spring.datasource.url=jdbc:h2:mem:events_venue_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=user1
spring.datasource.password=user123
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
