# Configuración de H2 para pruebas (Base de datos volátil en memoria)
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Para que Hibernate cree las tablas automáticamente en H2 basándose en tus Entidades
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Configuración JWT para pruebas (es necesaria para que levante el contexto de seguridad)
jwt.secret=UnaClaveSecretaMuyLargaYSeguraParaLasPruebas12345
jwt.expiration=3600000